import os
from collections import Counter

from constants import OutputFile
from logging_utils import setup_logger

from tacular._datagen.gno import build

logger = setup_logger(__name__, os.path.splitext(os.path.basename(__file__))[0])


def gen_gno(output_file: str = OutputFile.GNO):
    logger.info("\n" + "=" * 60)
    logger.info("GENERATING GNO DATA")
    logger.info("=" * 60)

    logger.info("  📖 Reading from: data_gen/data/gno.obo")
    # Parsing lives in tacular._datagen.gno (single source of truth, shared with `tacular update`).
    version, gno_entries = build("./data/GNOme.obo")
    logger.info(f"  ℹ️  Version: {version}")
    logger.info(f"  ✓ Parsed {len(gno_entries)} GNO entries")

    # Print stats
    missing_mono = sum(1 for mod in gno_entries if mod.monoisotopic_mass is None)
    missing_avg = sum(1 for mod in gno_entries if mod.average_mass is None)
    missing_formula = sum(1 for mod in gno_entries if mod.formula is None)

    if missing_mono > 0 or missing_avg > 0 or missing_formula > 0:
        logger.warning("\n  ⚠️  Data Completeness:")
        if missing_mono > 0:
            logger.warning(f"      Missing monoisotopic mass: {missing_mono}")
        if missing_avg > 0:
            logger.warning(f"      Missing average mass: {missing_avg}")
        if missing_formula > 0:
            logger.warning(f"      Missing formula: {missing_formula}")

    logger.info(f"\n  📝 Writing to: {output_file}")

    # see if there are any duplicates
    ids = [mod.id for mod in gno_entries]
    id_counts = Counter(ids)
    duplicate_ids = [mod_id for mod_id, count in id_counts.items() if count > 1]
    if duplicate_ids:
        logger.warning(f"  ⚠️  Found {len(duplicate_ids)} duplicate GNO IDs:")
        for dup_id in duplicate_ids:
            logger.warning(f"      Duplicate ID: {dup_id}")

    names = [mod.name for mod in gno_entries]
    name_counts = Counter(names)
    duplicate_names = [name for name, count in name_counts.items() if count > 1]
    if duplicate_names:
        logger.warning(f"  ⚠️  Found {len(duplicate_names)} duplicate GNO names:")
        for dup_name in duplicate_names:
            logger.warning(f"      Duplicate name: {dup_name}")

    # Generate the GNO entries
    entries: list[str] = []
    for mod in gno_entries:
        formula_str = f'"{mod.formula}"' if mod.formula is not None else "None"

        entry = f'''        "{mod.id}": GnoInfo(
        id="{mod.id}",
        name="{mod.name}",
        formula={formula_str},
        monoisotopic_mass={mod.monoisotopic_mass},
        average_mass={mod.average_mass},
        dict_composition={mod.dict_composition},
    ),'''
        entries.append(entry)

    entries_str = "\n".join(entries)

    # Write the complete file
    content = f'''"""Auto-generated GNO data"""
# DO NOT EDIT - generated by gen_gno.py

import warnings

from .dclass import GnoInfo

VERSION = "{version}"

try:
    GNO_GLYCANS: dict[str, GnoInfo] = {{
{entries_str}
    }}

    GNO_NAME_TO_ID: dict[str, str] = {{
        glycan.name: glycan.id
        for glycan in GNO_GLYCANS.values()
    }}
except Exception as e:
    warnings.warn(
        f"Exception in gno_data: {{e}}. Using empty dictionaries.",
        UserWarning,
        stacklevel=2
    )
    GNO_GLYCANS: dict[str, GnoInfo] = {{}}
    GNO_NAME_TO_ID: dict[str, str] = {{}}
'''

    with open(output_file, "w") as f:
        f.write(content)

    logger.info(f"✅ Successfully generated {output_file}")
    logger.info(f"   Total entries: {len(gno_entries)}")


if __name__ == "__main__":
    gen_gno()
