import os

from constants import OutputFile
from logging_utils import setup_logger

from tacular._datagen.unimod import build

logger = setup_logger(__name__, os.path.splitext(os.path.basename(__file__))[0])


def gen_uni(output_file: str = OutputFile.UNIMOD):
    logger.info("\n" + "=" * 60)
    logger.info("GENERATING UNIMOD DATA")
    logger.info("=" * 60)

    logger.info("  📖 Reading from: data_gen/data/UNIMOD.obo")
    # Parsing lives in tacular._datagen.unimod (single source of truth, shared with `tacular update`).
    version, unimod_entries = build("./data/UNIMOD.obo")
    logger.info(f"  ℹ️  Version: {version}")
    logger.info("  ✓ Parsed %d Unimod entries", len(unimod_entries))

    # print stats on number of entries missing mono avg or formula
    missing_mono = sum(1 for mod in unimod_entries if mod.monoisotopic_mass is None)
    missing_avg = sum(1 for mod in unimod_entries if mod.average_mass is None)
    missing_formula = sum(1 for mod in unimod_entries if mod.formula is None)
    if missing_mono > 0 or missing_avg > 0 or missing_formula > 0:
        logger.warning("\n  ⚠️  Data Completeness:")
        if missing_mono > 0:
            logger.warning("      Missing monoisotopic mass: %d", missing_mono)
        if missing_avg > 0:
            logger.warning("      Missing average mass: %d", missing_avg)
        if missing_formula > 0:
            logger.warning("      Missing formula: %d", missing_formula)

    logger.info("\n  📝 Writing to: %s", output_file)

    # Generate the Unimod entries
    entries: list[str] = []
    for mod in unimod_entries:
        # Format formula properly - None without quotes, strings with quotes
        formula_str = f'"{mod.formula}"' if mod.formula is not None else "None"

        entry = f'''    "{mod.id}": UnimodInfo(
        id="{mod.id}",
        name="{mod.name}",
        formula={formula_str},
        monoisotopic_mass={mod.monoisotopic_mass},
        average_mass={mod.average_mass},
        dict_composition={mod.dict_composition},
    ),'''
        entries.append(entry)

    entries_str = "\n".join(entries)

    # Write the complete file
    content = f'''"""Auto-generated Unimod data"""
# DO NOT EDIT - generated by gen_unimod.py

from .dclass import UnimodInfo
import warnings

VERSION = "{version}"


try:
    UNIMOD_MODIFICATIONS: dict[str, UnimodInfo] = {{
{entries_str}
    }}

    UNIMOD_NAME_TO_ID: dict[str, str] = {{
        mod.name: mod.id
        for mod in UNIMOD_MODIFICATIONS.values()
    }}
except Exception as e:
    warnings.warn(
        f"Exception in unimod_data: {{e}}. Using empty dictionaries.",
        UserWarning,
        stacklevel=2
    )
    UNIMOD_MODIFICATIONS: dict[str, UnimodInfo] = {{}}
    UNIMOD_NAME_TO_ID: dict[str, str] = {{}}
'''

    with open(output_file, "w") as f:
        f.write(content)

    logger.info("✅ Successfully generated %s", output_file)
    logger.info("   Total entries: %d", len(unimod_entries))


if __name__ == "__main__":
    gen_uni()
