import os

from constants import OutputFile
from logging_utils import setup_logger

from tacular._datagen.resid import build

logger = setup_logger(__name__, os.path.splitext(os.path.basename(__file__))[0])


def gen_resid(output_file: str = OutputFile.RESID):
    logger.info("\n" + "=" * 60)
    logger.info("GENERATING RESID DATA")
    logger.info("=" * 60)

    logger.info("  📖 Reading from: data_gen/data/PSI-MOD.obo")
    # Parsing lives in tacular._datagen.resid (single source of truth, shared with `tacular update`).
    version, resid_entries = build("./data/PSI-MOD.obo")
    logger.info(f"  ℹ️  Version: {version}")
    logger.info(f"  ✓ Parsed {len(resid_entries)} RESID entries")

    # Print stats on number of entries missing mono avg or formula
    missing_mono = sum(1 for mod in resid_entries if mod.monoisotopic_mass is None)
    missing_avg = sum(1 for mod in resid_entries if mod.average_mass is None)
    missing_formula = sum(1 for mod in resid_entries if mod.formula is None)

    if missing_mono > 0 or missing_avg > 0 or missing_formula > 0:
        logger.warning("\n  ⚠️  Data Completeness:")
        if missing_mono > 0:
            logger.warning(f"      Missing monoisotopic mass: {missing_mono}")
        if missing_avg > 0:
            logger.warning(f"      Missing average mass: {missing_avg}")
        if missing_formula > 0:
            logger.warning(f"      Missing formula: {missing_formula}")

    logger.info(f"\n  📝 Writing to: {output_file}")

    # Generate the RESID entries
    entries: list[str] = []
    for mod in resid_entries:
        # Format formula properly - None without quotes, strings with quotes
        formula_str = f'"{mod.formula}"' if mod.formula is not None else "None"

        entry = f'''        "{mod.id}": ResidInfo(
        id="{mod.id}",
        name="{mod.name}",
        formula={formula_str},
        monoisotopic_mass={mod.monoisotopic_mass},
        average_mass={mod.average_mass},
        dict_composition={mod.dict_composition},
    ),'''
        entries.append(entry)

    entries_str = "\n".join(entries)

    # Write the complete file
    content = f'''"""Auto-generated RESID data"""
# DO NOT EDIT - generated by gen_resid.py

import warnings

from .dclass import ResidInfo

VERSION = "{version}"

try:
    RESID_MODIFICATIONS: dict[str, ResidInfo] = {{
{entries_str}
    }}

    RESID_NAME_TO_ID: dict[str, str] = {{
        mod.name: mod.id
        for mod in RESID_MODIFICATIONS.values()
    }}
except Exception as e:
    warnings.warn(
        f"Exception in resid_data: {{e}}. Using empty dictionaries.",
        UserWarning,
        stacklevel=2
    )
    RESID_MODIFICATIONS: dict[str, ResidInfo] = {{}}
    RESID_NAME_TO_ID: dict[str, str] = {{}}
'''

    with open(output_file, "w") as f:
        f.write(content)

    logger.info(f"✅ Successfully generated {output_file}")
    logger.info(f"   Total entries: {len(resid_entries)}")


if __name__ == "__main__":
    gen_resid()
