import os

from constants import OutputFile
from logging_utils import setup_logger

from tacular._datagen.psimod import build

logger = setup_logger(__name__, os.path.splitext(os.path.basename(__file__))[0])


def gen_psi(output_file: str = OutputFile.PSIMOD):
    logger.info("\n" + "=" * 60)
    logger.info("GENERATING PSI-MOD DATA")
    logger.info("=" * 60)

    logger.info("  📖 Reading from: data_gen/data/PSI-MOD.obo")
    # Parsing lives in tacular._datagen.psimod (single source of truth, shared with `tacular update`).
    version, unimod_entries = build("./data/PSI-MOD.obo")
    logger.info(f"  ℹ️  Version: {version}")
    logger.info(f"  ✓ Parsed {len(unimod_entries)} PSI-MOD entries")

    # print stats on number of entries missing mono avg or formula
    missing_mono = sum(1 for mod in unimod_entries if mod.monoisotopic_mass is None)
    missing_avg = sum(1 for mod in unimod_entries if mod.average_mass is None)
    missing_formula = sum(1 for mod in unimod_entries if mod.formula is None)
    if missing_mono > 0 or missing_avg > 0 or missing_formula > 0:
        logger.warning("\n  ⚠️  Data Completeness:")
        if missing_mono > 0:
            logger.warning(f"      Missing monoisotopic mass: {missing_mono}")
        if missing_avg > 0:
            logger.warning(f"      Missing average mass: {missing_avg}")
        if missing_formula > 0:
            logger.warning(f"      Missing formula: {missing_formula}")

    # write a file of missing entries
    missing_entries_file = "./output/psimod_missing_entries.txt"
    logger.info(f"\n  📄 Writing missing entries to: {missing_entries_file}")
    with open(missing_entries_file, "w") as f:
        for mod in unimod_entries:
            if mod.monoisotopic_mass is None or mod.average_mass is None or mod.formula is None:
                f.write(f"{mod.id}\t{mod.name}\n")

    logger.info(f"\n  📝 Writing to: {output_file}")

    # Generate the Unimod entries
    entries: list[str] = []
    for mod in unimod_entries:
        # Format formula properly - None without quotes, strings with quotes
        formula_str = f'"{mod.formula}"' if mod.formula is not None else "None"

        entry = f'''    "{mod.id}": PsimodInfo(
        id="{mod.id}",
        name="{mod.name}",
        formula={formula_str},
        monoisotopic_mass={mod.monoisotopic_mass},
        average_mass={mod.average_mass},
        dict_composition={mod.dict_composition},
    ),'''
        entries.append(entry)

    entries_str = "\n".join(entries)

    # Write the complete file
    content = f'''"""Auto-generated PSI-MOD data"""
# DO NOT EDIT - generated by gen_psimod.py

import warnings

from .dclass import PsimodInfo

VERSION = "{version}"


try:
    PSI_MODIFICATIONS: dict[str, PsimodInfo] = {{
{entries_str}
    }}

    PSI_NAME_TO_ID: dict[str, str] = {{
        mod.name: mod.id
        for mod in PSI_MODIFICATIONS.values()
    }}
except Exception as e:
    warnings.warn(
        f"Exception in psimod_data: {{e}}. Using empty dictionaries.",
        UserWarning,
        stacklevel=2
    )
    PSI_MODIFICATIONS: dict[str, PsimodInfo] = {{}}
    PSI_NAME_TO_ID: dict[str, str] = {{}}
'''

    with open(output_file, "w") as f:
        f.write(content)

    logger.info(f"✅ Successfully generated {output_file}")
    logger.info(f"   Total entries: {len(unimod_entries)}")


if __name__ == "__main__":
    gen_psi()
