import os

from constants import OutputFile
from logging_utils import setup_logger

from tacular._datagen.xlmod import build

logger = setup_logger(__name__, os.path.splitext(os.path.basename(__file__))[0])


def gen_xl(output_file: str = OutputFile.XLMOD):
    logger.info("\n" + "=" * 60)
    logger.info("GENERATING XLMOD DATA")
    logger.info("=" * 60)

    logger.info("  📖 Reading from: data_gen/data/XLMod.obo")
    # Parsing lives in tacular._datagen.xlmod (single source of truth, shared with `tacular update`).
    version, entries_list = build("./data/XLMod.obo")
    logger.info(f"  ℹ️  Version: {version}")
    logger.info("  ✓ Parsed %d XLMOD entries", len(entries_list))

    # stats
    missing_mono = sum(1 for e in entries_list if e.monoisotopic_mass is None)
    missing_formula = sum(1 for e in entries_list if e.formula is None)
    if missing_mono > 0 or missing_formula > 0:
        logger.warning("\n  ⚠️  Data Completeness:")
        if missing_mono > 0:
            logger.warning("      Missing monoisotopic mass: %d", missing_mono)
        if missing_formula > 0:
            logger.warning("      Missing formula: %d", missing_formula)

    logger.info("\n  📝 Writing to: %s", output_file)

    entries: list[str] = []
    for mod in entries_list:
        formula_str = f'"{mod.formula}"' if mod.formula is not None else "None"

        entry = f'''        "{mod.id}": XlModInfo(
            id="{mod.id}",
            name="{mod.name}",
            formula={formula_str},
            monoisotopic_mass={mod.monoisotopic_mass},
            average_mass={mod.average_mass},
            dict_composition={mod.dict_composition},
    ),'''
        entries.append(entry)

    entries_str = "\n".join(entries)

    content = f'''"""Auto-generated XLMOD data"""
# DO NOT EDIT - generated by gen_xlmod.py

VERSION = "{version}"

import warnings

from .dclass import XlModInfo

try:
    XLMOD_MODIFICATIONS: dict[str, XlModInfo] = {{
{entries_str}
    }}

    XLMOD_NAME_TO_ID: dict[str, str] = {{
        mod.name: mod.id
        for mod in XLMOD_MODIFICATIONS.values()
    }}
except Exception as e:
    warnings.warn(
        f"Exception in xlmod_data: {{e}}. Using empty dictionaries.",
        UserWarning,
        stacklevel=2
    )
    XLMOD_MODIFICATIONS: dict[str, XlModInfo] = {{}}
    XLMOD_NAME_TO_ID: dict[str, str] = {{}}
'''

    with open(output_file, "w") as f:
        f.write(content)

    logger.info("✅ Successfully generated %s", output_file)
    logger.info("   Total entries: %d", len(entries_list))


if __name__ == "__main__":
    gen_xl()
