import os

from constants import OutputFile
from logging_utils import setup_logger

from tacular._datagen.uniprot_ptm import build

logger = setup_logger(__name__, os.path.splitext(os.path.basename(__file__))[0])


def _esc(s: str | None) -> str:
    """Escape a string for inclusion in generated Python source, or return 'None'."""
    if s is None:
        return "None"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _esc_tuple(t: tuple[str, ...]) -> str:
    """Serialize a tuple of strings for inclusion in generated Python source."""
    if not t:
        return "()"
    items = ", ".join('"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"' for v in t)
    return f"({items},)"


def gen_uniprot_ptm(output_file: str = OutputFile.UNIPROT_PTM):
    logger.info("\n" + "=" * 60)
    logger.info("GENERATING UniProt PTM DATA")
    logger.info("=" * 60)

    logger.info("  📖 Reading from: data_gen/data/ptmlist.txt")
    # Parsing lives in tacular._datagen.uniprot_ptm (single source of truth, shared with `tacular update`).
    version, entries = build("./data/ptmlist.txt")
    logger.info(f"  ℹ️  Version: {version}")
    logger.info(f"  ✓ Parsed {len(entries)} UniProt PTM entries")

    missing_mono = sum(1 for mod in entries if mod.monoisotopic_mass is None)
    missing_avg = sum(1 for mod in entries if mod.average_mass is None)
    missing_formula = sum(1 for mod in entries if mod.formula is None)
    if missing_mono or missing_avg or missing_formula:
        logger.warning("\n  ⚠️  Data Completeness:")
        if missing_mono:
            logger.warning(f"      Missing monoisotopic mass: {missing_mono}")
        if missing_avg:
            logger.warning(f"      Missing average mass: {missing_avg}")
        if missing_formula:
            logger.warning(f"      Missing formula: {missing_formula}")

    logger.info(f"\n  📝 Writing to: {output_file}")

    rendered: list[str] = []
    for mod in entries:
        formula_str = f'"{mod.formula}"' if mod.formula is not None else "None"
        name_escaped = mod.name.replace("\\", "\\\\").replace('"', '\\"')

        entry = f'''    "{mod.id}": UniprotPtmInfo(
        id="{mod.id}",
        name="{name_escaped}",
        formula={formula_str},
        monoisotopic_mass={mod.monoisotopic_mass},
        average_mass={mod.average_mass},
        dict_composition={mod.dict_composition},
        feature_key={_esc(mod.feature_key)},
        target={_esc(mod.target)},
        position_aa={_esc(mod.position_aa)},
        position_polypeptide={_esc(mod.position_polypeptide)},
        cellular_location={_esc(mod.cellular_location)},
        taxonomic_range={_esc_tuple(mod.taxonomic_range)},
        keywords={_esc_tuple(mod.keywords)},
        cross_references={_esc_tuple(mod.cross_references)},
    ),'''
        rendered.append(entry)

    entries_str = "\n".join(rendered)

    content = f'''"""Auto-generated UniProt PTM data"""
# DO NOT EDIT - generated by gen_uniprot_ptm.py

import warnings

from .dclass import UniprotPtmInfo

VERSION = "{version}"


try:
    UNIPROT_PTM_MODIFICATIONS: dict[str, UniprotPtmInfo] = {{
{entries_str}
    }}

    UNIPROT_PTM_NAME_TO_ID: dict[str, str] = {{
        mod.name: mod.id
        for mod in UNIPROT_PTM_MODIFICATIONS.values()
    }}
except Exception as e:
    warnings.warn(
        f"Exception in uniprot_ptm data: {{e}}. Using empty dictionaries.",
        UserWarning,
        stacklevel=2,
    )
    UNIPROT_PTM_MODIFICATIONS: dict[str, UniprotPtmInfo] = {{}}
    UNIPROT_PTM_NAME_TO_ID: dict[str, str] = {{}}
'''

    with open(output_file, "w") as f:
        f.write(content)

    logger.info(f"✅ Successfully generated {output_file}")
    logger.info(f"   Total entries: {len(entries)}")


if __name__ == "__main__":
    gen_uniprot_ptm()
