"""Auto-generated protease data"""
# DO NOT EDIT - generated by gen_proteases.py

from enum import StrEnum
from typing import Literal

from .dclass import ProteaseInfo


class Protease(StrEnum):
    """Enum of protease IDs"""
    ARG_C = "arg_c"
    ASP_N = "asp_n"
    CHYMOTRYPSIN = "chymotrypsin"
    CHYMOTRYPSIN_LOW = "chymotrypsin_low"
    CHYMOTRYPSIN_PROMEGA_HIGH = "chymotrypsin_promega_high"
    CHYMOTRYPSIN_PROMEGA_LOW = "chymotrypsin_promega_low"
    GLU_C = "glu_c"
    LYS_C = "lys_c"
    LYS_N = "lys_n"
    PROTEINASE_K = "proteinase_k"
    TRYPSIN = "trypsin"
    TRYPSIN_FULL = "trypsin_full"
    PROALANASE = "proalanase"
    PROALANASE_LOW = "proalanase_low"
    ELASTASE = "elastase"
    PEPSIN = "pepsin"
    THERMOLYSIN = "thermolysin"
    UNSPECIFIC = "unspecific"
    NO_ENZYME = "no_enzyme"

ProteaseLiteral = Literal[
    "arg_c",
    "asp_n",
    "chymotrypsin",
    "chymotrypsin_low",
    "chymotrypsin_promega_high",
    "chymotrypsin_promega_low",
    "glu_c",
    "lys_c",
    "lys_n",
    "proteinase_k",
    "trypsin",
    "trypsin_full",
    "proalanase",
    "proalanase_low",
    "elastase",
    "pepsin",
    "thermolysin",
    "unspecific",
    "no_enzyme",
]


PROTEASE_DICT: dict[Protease, ProteaseInfo] = {
Protease.ARG_C: ProteaseInfo(
    id=Protease.ARG_C,
    name="Arg-C",
    full_name="Clostripain",
    regex='(?<=R)',
),
Protease.ASP_N: ProteaseInfo(
    id=Protease.ASP_N,
    name="Asp-N",
    full_name="Peptidyl-Asp metalloendopeptidase",
    regex='(?=D)',
),
Protease.CHYMOTRYPSIN: ProteaseInfo(
    id=Protease.CHYMOTRYPSIN,
    name="Chymotrypsin",
    full_name="Chymotrypsin (high specificity)",
    regex='(?<=[FWYL])(?!P)',
),
Protease.CHYMOTRYPSIN_LOW: ProteaseInfo(
    id=Protease.CHYMOTRYPSIN_LOW,
    name="Chymotrypsin (low specificity)",
    full_name="Chymotrypsin without proline restriction",
    regex='(?<=[FWYL])',
),
Protease.CHYMOTRYPSIN_PROMEGA_HIGH: ProteaseInfo(
    id=Protease.CHYMOTRYPSIN_PROMEGA_HIGH,
    name="Chymotrypsin (Promega, high specificity)",
    full_name="Promega Chymotrypsin High Specificity",
    regex='(?<=[YFW])',
),
Protease.CHYMOTRYPSIN_PROMEGA_LOW: ProteaseInfo(
    id=Protease.CHYMOTRYPSIN_PROMEGA_LOW,
    name="Chymotrypsin (Promega, low specificity)",
    full_name="Promega Chymotrypsin Low Specificity",
    regex='(?<=[YFWLM])',
),
Protease.GLU_C: ProteaseInfo(
    id=Protease.GLU_C,
    name="Glu-C",
    full_name="Staphylococcus aureus V8 protease",
    regex='(?<=E)',
),
Protease.LYS_C: ProteaseInfo(
    id=Protease.LYS_C,
    name="Lys-C",
    full_name="Lysyl endopeptidase",
    regex='(?<=K)',
),
Protease.LYS_N: ProteaseInfo(
    id=Protease.LYS_N,
    name="Lys-N",
    full_name="Lysyl aminopeptidase",
    regex='(?=K)',
),
Protease.PROTEINASE_K: ProteaseInfo(
    id=Protease.PROTEINASE_K,
    name="Proteinase K",
    full_name="Tritirachium album proteinase K",
    regex='(?<=[AEFILTVWY])',
),
Protease.TRYPSIN: ProteaseInfo(
    id=Protease.TRYPSIN,
    name="Trypsin",
    full_name="Trypsin with proline restriction",
    regex='(?<=[KR])(?=[^P])',
),
Protease.TRYPSIN_FULL: ProteaseInfo(
    id=Protease.TRYPSIN_FULL,
    name="Trypsin (full cleavage)",
    full_name="Trypsin without proline restriction",
    regex='(?<=[KR])',
),
Protease.PROALANASE: ProteaseInfo(
    id=Protease.PROALANASE,
    name="Proalanase",
    full_name="Proalanase (high specificity)",
    regex='(?<=[PA])',
),
Protease.PROALANASE_LOW: ProteaseInfo(
    id=Protease.PROALANASE_LOW,
    name="Proalanase (low specificity)",
    full_name="Proalanase Low Specificity",
    regex='(?<=[PASG])',
),
Protease.ELASTASE: ProteaseInfo(
    id=Protease.ELASTASE,
    name="Elastase",
    full_name="Pancreatic elastase",
    regex='(?<=[AGSVLI])',
),
Protease.PEPSIN: ProteaseInfo(
    id=Protease.PEPSIN,
    name="Pepsin",
    full_name="Pepsin A",
    regex='(?<=[FLWY])',
),
Protease.THERMOLYSIN: ProteaseInfo(
    id=Protease.THERMOLYSIN,
    name="Thermolysin",
    full_name="Bacillus thermoproteolyticus thermolysin",
    regex='(?<![DE])(?=[AFILMV])',
),
Protease.UNSPECIFIC: ProteaseInfo(
    id=Protease.UNSPECIFIC,
    name="Non-specific cleavage",
    full_name="Non-specific protease",
    regex='()',
),
Protease.NO_ENZYME: ProteaseInfo(
    id=Protease.NO_ENZYME,
    name="No cleavage",
    full_name="No enzymatic digestion",
    regex='_',
),
}
